---
- name: webserver
  hosts: localhost
  user: ec2-user
  sudo: yes
  tasks:
        - name: install httpd
          yum: name=httpd state=installed
          sudo: yes
        - name: install mod_ssl
          yum: name=mod_ssl state=installed
          sudo: yes
        - name: Copy index.html file
          copy: src=/home/ec2-user/gitrepo/devops-assignment/index.html dest=/var/www/html/index.html
        - name: start apache
          service: name=httpd state=restarted
